# Generated by Django 5.0.6 on 2024-06-21 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_bsket_basket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
