# Generated by Django 5.0.6 on 2024-06-21 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
