# Generated by Django 5.0.6 on 2024-06-26 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_user_alter_cart_options_and_more'),
        ('product', '0009_productimageinline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
